# Generated by Django 4.0.5 on 2022-06-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0002_remove_slider_image4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='title2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
