# Generated by Django 4.0.5 on 2022-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_remove_contact_dial_code_remove_contact_main_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='address1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='address2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='address3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
