# Generated by Django 4.0.5 on 2022-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_slider_address1_slider_address2_slider_address3'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='address_number1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='address_number2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='address_number3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
