# Generated by Django 4.0.5 on 2022-06-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0007_remove_slider_address1_remove_slider_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField(max_length=500)),
            ],
        ),
    ]
