# Generated by Django 4.0.5 on 2022-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
